// Static data for deployment without a backend server
// This data is used when API calls fail (e.g., on static hosting)

export const staticServices = [
  {
    id: "static-1",
    name: "Shampoo & Blowdry",
    description: "A refreshing shampoo and professional blowdry for a polished, salon-fresh look. Perfect for any occasion.",
    duration: 30,
    price: "0.00",
    category: "Hair",
    imageUrl: "/images/service-hair.png",
    isActive: true,
  },
  {
    id: "static-2",
    name: "Signature Haircut & Style",
    description: "A personalized haircut and blow-dry style tailored to your face shape, hair texture, and lifestyle. Includes consultation and finishing touches.",
    duration: 60,
    price: "0.00",
    category: "Hair",
    imageUrl: "/images/service-hair.png",
    isActive: true,
  },
  {
    id: "static-3",
    name: "Full Color Treatment",
    description: "Complete hair color transformation including roots, full coverage, and glossing treatment for a rich, vibrant finish that lasts.",
    duration: 120,
    price: "0.00",
    category: "Hair",
    imageUrl: "/images/service-color.png",
    isActive: true,
  },
];

export const staticProducts = [
  {
    id: "static-p1",
    name: "Moroccan Argan Oil Serum",
    description: "Premium argan oil that tames frizz, adds shine, and protects hair from heat damage. A must-have for silky smooth locks.",
    price: "34.99",
    imageUrl: "/images/products-banner.png",
    category: "Hair Care",
    amazonUrl: "https://www.amazon.com",
    inStock: true,
    featured: true,
  },
  {
    id: "static-p2",
    name: "Keratin Repair Shampoo",
    description: "Professional-grade shampoo infused with keratin protein to strengthen and repair damaged hair from root to tip.",
    price: "28.50",
    imageUrl: "/images/products-banner.png",
    category: "Hair Care",
    amazonUrl: "https://www.amazon.com",
    inStock: true,
    featured: true,
  },
  {
    id: "static-p3",
    name: "Hydrating Hair Mask",
    description: "Deep conditioning mask with avocado oil and biotin for intense moisture repair. Use weekly for transformative results.",
    price: "42.00",
    imageUrl: "/images/products-banner.png",
    category: "Hair Care",
    amazonUrl: "https://www.amazon.com",
    inStock: true,
    featured: true,
  },
  {
    id: "static-p4",
    name: "Heat Protectant Spray",
    description: "Lightweight thermal protectant spray that shields hair up to 450F. Prevents damage from blow dryers and flat irons.",
    price: "19.99",
    imageUrl: "/images/products-banner.png",
    category: "Styling",
    amazonUrl: "https://www.amazon.com",
    inStock: true,
    featured: false,
  },
  {
    id: "static-p5",
    name: "Vitamin E Cuticle Oil",
    description: "Nourishing cuticle oil enriched with vitamin E and jojoba oil. Keeps nails and cuticles healthy and hydrated.",
    price: "14.99",
    imageUrl: "/images/products-banner.png",
    category: "Nail Care",
    amazonUrl: "https://www.amazon.com",
    inStock: true,
    featured: false,
  },
  {
    id: "static-p6",
    name: "Hydrating Face Serum",
    description: "Lightweight hyaluronic acid serum that delivers deep hydration for plump, dewy skin. Perfect for all skin types.",
    price: "38.00",
    imageUrl: "/images/products-banner.png",
    category: "Skin Care",
    amazonUrl: "https://www.amazon.com",
    inStock: true,
    featured: false,
  },
];

export const staticBooks = [
  {
    id: "static-b1",
    title: "The Sound of an Ordinary Life",
    author: "Alis Cerrahyan",
    description: "A powerful memoir exploring inner healing and spiritual growth. Alis shares her deeply personal journey of overcoming a painful childhood, navigating dysfunctional family dynamics, motherhood, migration, and building her salon business — all through the lens of faith and resilience. A story of finding God's unconditional love amidst life's deepest struggles.",
    coverImageUrl: "/images/book-sound-ordinary-life.png",
    amazonUrl: "https://www.amazon.com/Sound-Ordinary-Life-Alis-Cerrahyan/dp/B0DKCK72HB",
    isbn: "9798343576689",
    genre: "Memoir / Spiritual",
    year: 2024,
    publisher: null,
    awards: "Literary Titan Gold Book Award (Non-Fiction), International Impact Book Awards Winner",
    featured: true,
    sortOrder: 1,
  },
  {
    id: "static-b2",
    title: "Dance Like Nobody's Watching",
    author: "Alis Cerrahyan",
    description: "An inspirational memoir about living authentically and overcoming limitations. Alis invites readers to embrace who they truly are, let go of fear and self-doubt, and dance through life with faith, courage, and self-acceptance. A heartfelt call to personal authenticity.",
    coverImageUrl: "/images/book-dance.png",
    amazonUrl: "https://www.amazon.com/Dance-Like-Nobodys-Watching-Cerrahyan/dp/1643005731",
    isbn: "9781643005737",
    genre: "Memoir / Inspirational",
    year: 2018,
    publisher: "Covenant Books",
    awards: null,
    featured: true,
    sortOrder: 2,
  },
  {
    id: "static-b3",
    title: "Shadows Prove the Sunlight",
    author: "Alis Cerrahyan",
    description: "A collection of reflective, metaphorical, and thought-provoking essays drawn from personal experience. Alis explores how life's darkest moments can become proof of the light that exists beyond them — offering hope, wisdom, and spiritual insight to readers seeking encouragement.",
    coverImageUrl: "/images/book-shadows.png",
    amazonUrl: "https://www.amazon.com/s?k=alis+cerrahyan+shadows+prove+the+sunlight",
    isbn: null,
    genre: "Inspirational / Spiritual",
    year: null,
    publisher: null,
    awards: null,
    featured: true,
    sortOrder: 3,
  },
  {
    id: "static-b4",
    title: "Heaven On Earth",
    author: "Alis Cerrahyan",
    description: "A spiritual and faith-based exploration of finding heaven in our everyday lives. Alis writes about God's unconditional love, helping readers who struggle with discouragement or defeat discover spiritual growth, resilience, and inner peace right where they are.",
    coverImageUrl: "/images/book-heaven.png",
    amazonUrl: "https://www.amazon.com/Heaven-Earth-Alis-Cerrahyan/dp/1093127813",
    isbn: "9781093127812",
    genre: "Spiritual / Faith-based",
    year: 2019,
    publisher: null,
    awards: null,
    featured: true,
    sortOrder: 4,
  },
];

export const staticPaintings = [
  {
    id: "static-pt1",
    title: "Mountain Sunset Landscape",
    description: "A breathtaking oil painting capturing the warm glow of sunset over majestic mountains, with rich golden and purple tones reflecting off peaceful waters below.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis11.jpg",
    size: '16" x 20"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: true,
    externalUrl: "https://alis.webador.com/page-2",
    featured: true,
    sortOrder: 1,
  },
  {
    id: "static-pt2",
    title: "Autumn River Scene",
    description: "A serene autumn landscape with golden and amber trees lining a gentle river, painted with soft, expressive brushwork.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis12-1.jpg",
    size: '11" x 14"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: false,
    externalUrl: "https://alis.webador.com/page-2",
    featured: true,
    sortOrder: 2,
  },
  {
    id: "static-pt3",
    title: "Cherry Tree with Birds",
    description: "A vibrant cherry blossom tree alive with colorful birds perched among pink and white blooms against a soft sky.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/cherrytreebirds-standard.jpg",
    size: '16" x 20"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: false,
    externalUrl: "https://alis.webador.com/page-2",
    featured: true,
    sortOrder: 3,
  },
  {
    id: "static-pt4",
    title: "Misty Mountain Lake",
    description: "A tranquil mountain lake scene with misty peaks reflected in still waters, evoking a sense of peace and natural wonder.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis13.jpg",
    size: '16" x 20"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: true,
    externalUrl: "https://alis.webador.com/page-2",
    featured: true,
    sortOrder: 4,
  },
  {
    id: "static-pt5",
    title: "Golden Meadow Path",
    description: "A sunlit path winding through golden meadows with wildflowers, leading the eye toward a distant horizon under a luminous sky.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis14.jpg",
    size: '16" x 20"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: true,
    externalUrl: "https://alis.webador.com/page-2",
    featured: false,
    sortOrder: 5,
  },
  {
    id: "static-pt6",
    title: "Woodland Stream",
    description: "A peaceful woodland scene with a gentle stream flowing through autumn-colored trees, capturing the beauty of nature's quiet moments.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis15.jpg",
    size: '16" x 20"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: true,
    externalUrl: "https://alis.webador.com/page-2",
    featured: false,
    sortOrder: 6,
  },
  {
    id: "static-pt7",
    title: "Twilight Forest",
    description: "An enchanting forest scene bathed in twilight hues, with tall trees casting long shadows over a carpet of fallen leaves.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis16.jpg",
    size: '16" x 20"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: false,
    externalUrl: "https://alis.webador.com/page-2",
    featured: false,
    sortOrder: 7,
  },
  {
    id: "static-pt8",
    title: "Countryside Cottage",
    description: "A charming countryside cottage nestled among lush greenery and colorful flowers, painted with warm, inviting tones.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis17.jpg",
    size: '14" x 18"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: false,
    externalUrl: "https://alis.webador.com/page-2",
    featured: false,
    sortOrder: 8,
  },
  {
    id: "static-pt9",
    title: "River Valley Vista",
    description: "A panoramic river valley view with rolling hills and dramatic cloud formations, showcasing the grandeur of the natural landscape.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/alis18.jpg",
    size: '14" x 18"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: false,
    externalUrl: "https://alis.webador.com/page-2",
    featured: false,
    sortOrder: 9,
  },
  {
    id: "static-pt10",
    title: "Birds in Spring",
    description: "Colorful birds perched on flowering branches, a celebration of spring's arrival with delicate blossoms and vibrant plumage.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/birds-1.jpg",
    size: '16" x 20"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: true,
    externalUrl: "https://alis.webador.com/page-2",
    featured: true,
    sortOrder: 10,
  },
  {
    id: "static-pt11",
    title: "Cardinal Pair",
    description: "A striking pair of cardinals perched together among pine branches, their brilliant red plumage standing out against the winter greenery.",
    imageUrl: "https://primary.jwwb.nl/public/i/h/r/temp-adpaktvvshxsioqjiwik/cardinals-standard.jpg",
    size: '11" x 14"',
    medium: "Oil on Canvas",
    year: null,
    price: null,
    isSold: true,
    externalUrl: "https://alis.webador.com/page-2",
    featured: true,
    sortOrder: 11,
  },
];

export const staticReviews = [
  {
    id: "review-1",
    clientName: "Maria T.",
    rating: 5,
    content: "Alis is absolutely amazing! She took the time to understand exactly what I wanted and the results were beyond my expectations. My hair has never looked this good. The salon has such a warm, welcoming atmosphere.",
    isApproved: true,
    createdAt: "2025-12-15T10:30:00Z",
  },
  {
    id: "review-2",
    clientName: "Jennifer L.",
    rating: 5,
    content: "I've been coming to Alis' for over two years and she never disappoints. Her attention to detail is unmatched. The balayage she did for me was perfection — so many compliments!",
    isApproved: true,
    createdAt: "2025-11-28T14:00:00Z",
  },
  {
    id: "review-3",
    clientName: "Samantha R.",
    rating: 5,
    content: "Best salon experience I've ever had. Alis really listens and her skills are incredible. The facial treatment left my skin glowing for weeks. Highly recommend to anyone looking for a true professional.",
    isApproved: true,
    createdAt: "2025-11-10T09:00:00Z",
  },
  {
    id: "review-4",
    clientName: "Diana K.",
    rating: 4,
    content: "Wonderful experience from start to finish. The salon is beautiful and Alis is so talented. I got a full color treatment and it turned out exactly as I imagined. Will definitely be back!",
    isApproved: true,
    createdAt: "2025-10-22T16:00:00Z",
  },
  {
    id: "review-5",
    clientName: "Rachel M.",
    rating: 5,
    content: "Alis has a gift — she transformed my damaged hair into something beautiful. The deep conditioning treatment was heavenly. Her books and paintings around the salon add such a personal, artistic touch. Love it here!",
    isApproved: true,
    createdAt: "2025-10-05T11:30:00Z",
  },
];

// Map of API endpoints to static fallback data
export const staticDataMap: Record<string, any[]> = {
  "/api/services": staticServices,
  "/api/products": staticProducts,
  "/api/books": staticBooks,
  "/api/paintings": staticPaintings,
  "/api/reviews": staticReviews,
};
